/** Trusted platform APIs. Never expose the repository/coordinator to a native Host. */
export { SQLiteDomainRepository } from './domain/sqlite.ts'
export type { DomainOwner, DomainRecord, DomainRepository, DomainState, DomainDesiredState } from './domain/repository.ts'
export { DomainRuntimeCoordinator } from './runtime/coordinator.ts'
export type { RuntimeProvider, RuntimeHandle, RuntimeReady, RuntimeSpec, RuntimeAdmission } from './runtime/provider.ts'
export { DockerRuntimeProvider } from './runtime/providers/docker.ts'
export type { DockerRuntimeOptions } from './runtime/providers/docker.ts'
export { LocalProcessRuntimeProvider } from './runtime/providers/local-process.ts'
export type { LocalRuntimeCommand } from './runtime/providers/local-process.ts'
export { createDomainIngress } from './ingress/server.ts'
export type { DomainIngressOptions } from './ingress/server.ts'
export { MemoryDomainSessions } from './ingress/authentication.ts'
export type { DomainAuthenticator, AuthenticatedSession } from './ingress/authentication.ts'
export const DSH_RUNTIME_VERSION = '0.1.5-rc.2'
