apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dsh-environment-runtime
rules:
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, create, patch]
  - apiGroups: [""]
    resources: [persistentvolumeclaims, serviceaccounts]
    verbs: [get, create]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [services]
    verbs: [get, list]
  - apiGroups: [discovery.k8s.io]
    resources: [endpointslices]
    verbs: [get, list]
  - apiGroups: [networking.k8s.io]
    resources: [networkpolicies]
    verbs: [get, create]
  - apiGroups: [agents.x-k8s.io]
    resources: [sandboxes]
    verbs: [get, list, create, patch, delete]
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get]
